/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;


import assignment2_car.Assignment2_Car;
import assignment2_car.Directory_Car;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mhetr
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
public String checkbox;
private JPanel userProcessContainer;
private Directory_Car carDirectory;
   public CreateJPanel(JPanel userProcessContainer, Directory_Car carDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.carDirectory=carDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEnterDetails = new javax.swing.JLabel();
        lblTransitLevel = new javax.swing.JLabel();
        lblBrand1 = new javax.swing.JLabel();
        txtBrand1 = new javax.swing.JTextField();
        lblModelNo = new javax.swing.JLabel();
        txtmodelNo1 = new javax.swing.JTextField();
        lblSerialNo = new javax.swing.JLabel();
        txtserialNo1 = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCity1 = new javax.swing.JTextField();
        lblCost = new javax.swing.JLabel();
        txtCost1 = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtManufactureYear1 = new javax.swing.JTextField();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        lblAvailable = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtTransitLevel1 = new javax.swing.JComboBox();
        txtmaintenanceCertificate1 = new javax.swing.JComboBox();
        lblRegisteredWithUber = new javax.swing.JLabel();
        txtRegisteredWithUber1 = new javax.swing.JComboBox();
        lblSeatcount = new javax.swing.JLabel();
        txtNoOfSeats1 = new javax.swing.JTextField();
        checkBox1 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(102, 102, 127));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblEnterDetails.setBackground(new java.awt.Color(0, 0, 0));
        lblEnterDetails.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblEnterDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnterDetails.setText("Enter Car Details");

        lblTransitLevel.setBackground(new java.awt.Color(0, 0, 0));
        lblTransitLevel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTransitLevel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTransitLevel.setText("Transit Level:");

        lblBrand1.setBackground(new java.awt.Color(0, 0, 0));
        lblBrand1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblBrand1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblBrand1.setText("Brand Name:");

        txtBrand1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtBrand1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtBrand1.setBorder(null);
        txtBrand1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBrand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrand1ActionPerformed(evt);
            }
        });

        lblModelNo.setBackground(new java.awt.Color(0, 0, 0));
        lblModelNo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblModelNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblModelNo.setText("Model Number:");

        txtmodelNo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtmodelNo1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtmodelNo1.setBorder(null);
        txtmodelNo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblSerialNo.setBackground(new java.awt.Color(0, 0, 0));
        lblSerialNo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSerialNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSerialNo.setText("Serial Number:");

        txtserialNo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtserialNo1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtserialNo1.setBorder(null);
        txtserialNo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtserialNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserialNo1ActionPerformed(evt);
            }
        });

        lblCity.setBackground(new java.awt.Color(0, 0, 0));
        lblCity.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCity.setText("City Available:");

        txtCity1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCity1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCity1.setBorder(null);
        txtCity1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblCost.setBackground(new java.awt.Color(0, 0, 0));
        lblCost.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCost.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCost.setText("Cost");

        txtCost1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCost1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCost1.setBorder(null);
        txtCost1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCost1ActionPerformed(evt);
            }
        });

        lblYear.setBackground(new java.awt.Color(0, 0, 0));
        lblYear.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblYear.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblYear.setText("Manufacture Year:");

        txtManufactureYear1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtManufactureYear1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtManufactureYear1.setBorder(null);
        txtManufactureYear1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblMaintenanceCertificate.setBackground(new java.awt.Color(0, 0, 0));
        lblMaintenanceCertificate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblMaintenanceCertificate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMaintenanceCertificate.setText("Maintenance Certificate:");

        lblAvailable.setBackground(new java.awt.Color(0, 0, 0));
        lblAvailable.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAvailable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAvailable.setText("Available:");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 204, 255));
        btnBack.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 0, 51));
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtTransitLevel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTransitLevel1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Prime", "SUV", "Mini", "Micro", " " }));
        txtTransitLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransitLevel1ActionPerformed(evt);
            }
        });

        txtmaintenanceCertificate1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtmaintenanceCertificate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Valid", "Expired" }));
        txtmaintenanceCertificate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaintenanceCertificate1ActionPerformed(evt);
            }
        });

        lblRegisteredWithUber.setBackground(new java.awt.Color(0, 0, 0));
        lblRegisteredWithUber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblRegisteredWithUber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRegisteredWithUber.setText("Registered with Uber:");

        txtRegisteredWithUber1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtRegisteredWithUber1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Yes", "No" }));
        txtRegisteredWithUber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisteredWithUber1ActionPerformed(evt);
            }
        });

        lblSeatcount.setBackground(new java.awt.Color(0, 0, 0));
        lblSeatcount.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSeatcount.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSeatcount.setText("No of Seats:");

        txtNoOfSeats1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNoOfSeats1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNoOfSeats1.setBorder(null);
        txtNoOfSeats1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        checkBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTransitLevel)
                        .addGap(0, 479, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBrand1)
                                    .addComponent(lblCost)
                                    .addComponent(lblCity)
                                    .addComponent(lblAvailable))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtCost1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTransitLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(120, 120, 120)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblSeatcount)
                                                    .addComponent(lblModelNo)
                                                    .addComponent(lblYear)
                                                    .addComponent(lblSerialNo)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblRegisteredWithUber))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblMaintenanceCertificate)
                                .addGap(18, 18, 18)
                                .addComponent(txtmaintenanceCertificate1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtManufactureYear1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtmodelNo1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtNoOfSeats1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtserialNo1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(txtRegisteredWithUber1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterDetails)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBrand1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBrand1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtserialNo1)
                        .addComponent(lblSerialNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmodelNo1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCity)
                        .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblModelNo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTransitLevel)
                        .addComponent(txtTransitLevel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNoOfSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSeatcount))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear)
                            .addComponent(txtManufactureYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCost)
                            .addComponent(txtCost1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRegisteredWithUber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkBox1)
                    .addComponent(lblAvailable)
                    .addComponent(lblRegisteredWithUber, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaintenanceCertificate)
                    .addComponent(txtmaintenanceCertificate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(239, 239, 239)
                .addComponent(btnSave)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCost1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCost1ActionPerformed

    
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String transitLevel = txtTransitLevel1.getSelectedItem().toString();
        if (transitLevel == null || transitLevel.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select a Transit Level!");
            return;
        }
        String brand = txtBrand1.getText();
        if (brand == null || brand.equals("")) {
            JOptionPane.showMessageDialog(null, "Brand Name is empty!");
            return;
        }
        String modelNo = txtmodelNo1.getText();
        if (modelNo == null || modelNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Model Number is empty!");
            return;
        }
        String serialNo = txtserialNo1.getText();
        if (serialNo == null || serialNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Serial Number is empty!");
            return;
        }
        
        String city = txtCity1.getText();
        if (city == null || city.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid City Name!");
            return;
        }
       
        
        
        String seatCount = txtNoOfSeats1.getText();
        try{
            Integer.parseInt(seatCount);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter in a integer value for No of Seats");
            return;
        }
        String cost = txtCost1.getText();
        try{
            Double.parseDouble(cost);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter in a Double value for Cost");
            return;
        }
        String manufactureYear = txtManufactureYear1.getText();
        try{
            Integer.parseInt(manufactureYear);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please enter in a Integer value for Manufactured Year");
            return;
        }
        String maintenanceCertificate = txtmaintenanceCertificate1.getSelectedItem().toString();
        if (maintenanceCertificate == null || maintenanceCertificate.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select the status of maintenance certificate");
            return;
        }
        
        String registeredwithUber = txtRegisteredWithUber1.getSelectedItem().toString();
        if (registeredwithUber == null || registeredwithUber.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select Registration with Uber");
            return;
        }
        DateFormat dateformat = new SimpleDateFormat("MM:dd:YYYY");
        Date dateObj = new Date();
        String j = dateformat.format(dateObj);
      

        Assignment2_Car car = carDirectory.addCar();
        car.setTransitLevel(transitLevel);
        car.setbrand(brand);
        car.setmodelNo(modelNo);
        car.setserialNo(serialNo);
        
        car.setCity(city);
        car.setSeatCount(Integer.parseInt(seatCount));
        car.setPrice(Double.parseDouble(cost));
        car.setManufactureYear(Integer.parseInt(manufactureYear));
        car.setmaintenanceCertificate(maintenanceCertificate);
        
        if(checkBox1.isSelected())
        {
            car.setAvailablity("Yes");
            
        }
        else
        {
            car.setAvailablity("No");
        }
       // car.setAvailablity(checkbox);
        car.setregisteredwithUber(registeredwithUber);
        car.setDate(j);

        JOptionPane.showMessageDialog(null, "Car is Registered Successfully!");
        
        txtCity1.setText("");
      
        txtNoOfSeats1.setText("");
        txtCost1.setText("");
        txtManufactureYear1.setText("");
        txtmaintenanceCertificate1.setSelectedItem("Select");
        txtRegisteredWithUber1.setSelectedItem("Select");
        
        checkBox1.setSelected(Boolean.parseBoolean(""));

        txtTransitLevel1.setSelectedItem("Select");
        txtBrand1.setText("");
        txtmodelNo1.setText("");
        txtserialNo1.setText("");
       
        

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtTransitLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransitLevel1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTransitLevel1ActionPerformed

    private void txtmaintenanceCertificate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaintenanceCertificate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaintenanceCertificate1ActionPerformed

    private void txtRegisteredWithUber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisteredWithUber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisteredWithUber1ActionPerformed

    private void checkBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_checkBox1ActionPerformed

    private void txtBrand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrand1ActionPerformed

    private void txtserialNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserialNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserialNo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblBrand1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblEnterDetails;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblModelNo;
    private javax.swing.JLabel lblRegisteredWithUber;
    private javax.swing.JLabel lblSeatcount;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblTransitLevel;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextField txtBrand1;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtCost1;
    private javax.swing.JTextField txtManufactureYear1;
    private javax.swing.JTextField txtNoOfSeats1;
    private javax.swing.JComboBox txtRegisteredWithUber1;
    private javax.swing.JComboBox txtTransitLevel1;
    private javax.swing.JComboBox txtmaintenanceCertificate1;
    private javax.swing.JTextField txtmodelNo1;
    private javax.swing.JTextField txtserialNo1;
    // End of variables declaration//GEN-END:variables
}
