/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import assignment2_car.Assignment2_Car;
import assignment2_car.Directory_Car;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mhetr
 */
public class ManageJPanel extends javax.swing.JPanel {
 
    private Directory_Car carDirectory;
    private JPanel userProcessContainer;

    /**
     * Creates new form ManageJPanel
     */
    
  ManageJPanel(JPanel userProcessContainer, Directory_Car carDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.carDirectory = carDirectory;
        //this.car=car;
        populateTable();
    }
  private void populateTable()
    {
        DefaultTableModel tmodel = (DefaultTableModel) tblCarDetails.getModel();
        tmodel.setRowCount(0);
        for(Assignment2_Car car: carDirectory.getCarList())
        {
            Object[] row = new Object[4];
            row[0] = car;
            row[1] = car.getmodelNo();
            row[2] = car.getAvailablity();
            row[3] = car.getPrice();
            
            tmodel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarDetails = new javax.swing.JTable();
        btnCity1 = new javax.swing.JButton();
        txtCity = new javax.swing.JTextField();
        btnDelete1 = new javax.swing.JButton();
        btnBrand1 = new javax.swing.JButton();
        txtBrand = new javax.swing.JTextField();
        btnYear = new javax.swing.JButton();
        txtYearSearch = new javax.swing.JTextField();
        btnModelNo1 = new javax.swing.JButton();
        txtModelNo = new javax.swing.JTextField();
        btnCertificate = new javax.swing.JButton();
        btnViewDetails1 = new javax.swing.JButton();
        lblMinSeats = new javax.swing.JLabel();
        txtMinSeats = new javax.swing.JTextField();
        lblMinSeats1 = new javax.swing.JLabel();
        txtMaxSeats = new javax.swing.JTextField();
        btnSeatCapacity1 = new javax.swing.JButton();
        btnFirstAvailableCar1 = new javax.swing.JButton();
        btnLastUpdate = new javax.swing.JButton();
        txtLastUpdated = new javax.swing.JTextField();
        btnAllAvailableCar1 = new javax.swing.JButton();
        btnUnavailableCar1 = new javax.swing.JButton();
        btnserialNoS1 = new javax.swing.JButton();
        txtserialNoS = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(107, 107, 127));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblCarDetails.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblCarDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Model Number", "Availablity", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCarDetails);

        btnCity1.setBackground(new java.awt.Color(255, 255, 255));
        btnCity1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCity1.setText("Search by City");
        btnCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCity1ActionPerformed(evt);
            }
        });

        txtCity.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        btnDelete1.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnDelete1.setText("Delete");
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });

        btnBrand1.setBackground(new java.awt.Color(255, 255, 255));
        btnBrand1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnBrand1.setText("Search by Brand");
        btnBrand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrand1ActionPerformed(evt);
            }
        });

        txtBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        btnYear.setBackground(new java.awt.Color(255, 255, 255));
        btnYear.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnYear.setText("Search by Manufactured Year");
        btnYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYearActionPerformed(evt);
            }
        });

        txtYearSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtYearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearSearchActionPerformed(evt);
            }
        });

        btnModelNo1.setBackground(new java.awt.Color(255, 255, 255));
        btnModelNo1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnModelNo1.setText("Search by Model Number");
        btnModelNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNo1ActionPerformed(evt);
            }
        });

        txtModelNo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelNoActionPerformed(evt);
            }
        });

        btnCertificate.setBackground(new java.awt.Color(255, 255, 255));
        btnCertificate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCertificate.setText("Expired Maintenance Certificate");
        btnCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCertificateActionPerformed(evt);
            }
        });

        btnViewDetails1.setBackground(new java.awt.Color(255, 255, 255));
        btnViewDetails1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnViewDetails1.setText("View Details of selected Car");
        btnViewDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetails1ActionPerformed(evt);
            }
        });

        lblMinSeats.setBackground(new java.awt.Color(0, 0, 0));
        lblMinSeats.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMinSeats.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMinSeats.setText("Min Seats:");

        txtMinSeats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMinSeats.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtMinSeats.setBorder(null);
        txtMinSeats.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblMinSeats1.setBackground(new java.awt.Color(0, 0, 0));
        lblMinSeats1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMinSeats1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMinSeats1.setText("Max Seats:");

        txtMaxSeats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMaxSeats.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtMaxSeats.setBorder(null);
        txtMaxSeats.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSeatCapacity1.setBackground(new java.awt.Color(255, 255, 255));
        btnSeatCapacity1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSeatCapacity1.setText("Seat Capacity");
        btnSeatCapacity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeatCapacity1ActionPerformed(evt);
            }
        });

        btnFirstAvailableCar1.setBackground(new java.awt.Color(255, 255, 255));
        btnFirstAvailableCar1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnFirstAvailableCar1.setText("1st Available Car");
        btnFirstAvailableCar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstAvailableCar1ActionPerformed(evt);
            }
        });

        btnLastUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnLastUpdate.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnLastUpdate.setText("Last Updated on");
        btnLastUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastUpdateActionPerformed(evt);
            }
        });

        txtLastUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastUpdatedActionPerformed(evt);
            }
        });

        btnAllAvailableCar1.setBackground(new java.awt.Color(255, 255, 255));
        btnAllAvailableCar1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAllAvailableCar1.setText("All Available Cars");
        btnAllAvailableCar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllAvailableCar1ActionPerformed(evt);
            }
        });

        btnUnavailableCar1.setBackground(new java.awt.Color(255, 255, 255));
        btnUnavailableCar1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnUnavailableCar1.setText("Unavailable Cars");
        btnUnavailableCar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnavailableCar1ActionPerformed(evt);
            }
        });

        btnserialNoS1.setBackground(new java.awt.Color(255, 255, 255));
        btnserialNoS1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnserialNoS1.setText("Search by Serial No");
        btnserialNoS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnserialNoS1ActionPerformed(evt);
            }
        });

        txtserialNoS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtserialNoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserialNoSActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Registered with Uber");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnSeatCapacity1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnBrand1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnModelNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtYearSearch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                        .addComponent(txtBrand, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lblMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCertificate)
                                .addGap(106, 106, 106))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblMinSeats1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnserialNoS1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(txtserialNoS, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(btnCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnLastUpdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                            .addComponent(txtLastUpdated))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnViewDetails1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnFirstAvailableCar1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(btnAllAvailableCar1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnUnavailableCar1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails1)
                    .addComponent(btnFirstAvailableCar1)
                    .addComponent(btnAllAvailableCar1)
                    .addComponent(btnUnavailableCar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCertificate))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModelNo1)
                            .addComponent(txtModelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtserialNoS, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnserialNoS1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrand1)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCity1)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYear)
                    .addComponent(txtYearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLastUpdate)
                    .addComponent(txtLastUpdated, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeatCapacity1)
                    .addComponent(txtMinSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinSeats)
                    .addComponent(lblMinSeats1)
                    .addComponent(txtMaxSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(btnDelete1)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCity1ActionPerformed
        // TODO add your handling code here:
        
        String city = txtCity.getText();
        ArrayList<Assignment2_Car> cityList = carDirectory.cityCarlist(city);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,cityList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCity1ActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCarDetails.getSelectedRow();
        if(selectedRow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the car details", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION);
            {
                Assignment2_Car car = (Assignment2_Car) tblCarDetails.getValueAt(selectedRow, 0);
                carDirectory.deleteCar(car);
                populateTable();
            }

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnBrand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrand1ActionPerformed
        // TODO add your handling code here:
       
        String brand = txtBrand.getText();
        ArrayList<Assignment2_Car> brandList = carDirectory.brandCarList(brand);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,brandList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBrand1ActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void btnYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYearActionPerformed
        // TODO add your handling code here:
       
        int manufactureYear = Integer.parseInt(txtYearSearch.getText());
        ArrayList<Assignment2_Car> yearList = carDirectory.manufactureYearCar(manufactureYear);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,yearList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnYearActionPerformed

    private void txtYearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearSearchActionPerformed

    private void btnserialNoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserialNoSearchActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnserialNoSearchActionPerformed

    private void txtserialNoSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserialNoSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserialNoSearchActionPerformed

    private void btnModelNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNo1ActionPerformed
        // TODO add your handling code here:
        
        String modelNo = txtModelNo.getText();
        ArrayList<Assignment2_Car> modelList = carDirectory.modelNoList(modelNo);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,modelList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnModelNo1ActionPerformed

    private void txtModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelNoActionPerformed

    private void btnregisteredwithUberSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisteredwithUberSearchActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_btnregisteredwithUberSearchActionPerformed

    private void btnCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCertificateActionPerformed
        // TODO add your handling code here:
        
        String expired = "Expired";
        ArrayList<Assignment2_Car> expiredCertiList = carDirectory.expiredCertificate(expired);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,expiredCertiList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCertificateActionPerformed

    private void btnViewDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetails1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCarDetails.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Assignment2_Car car = (Assignment2_Car) tblCarDetails.getValueAt(selectedRow, 0);
            ViewJPanel panel = new ViewJPanel(userProcessContainer, car, carDirectory);
            userProcessContainer.add("ViewJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewDetails1ActionPerformed

    private void btnSeatCapacity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeatCapacity1ActionPerformed
        // TODO add your handling code here:
        String minSeats = txtMinSeats.getText();
        String maxseats = txtMaxSeats.getText();
        int minS = minSeats.equals("") ? Integer.MIN_VALUE : Integer.parseInt(minSeats);
        int maxS = maxseats.equals("") ? Integer.MAX_VALUE : Integer.parseInt(maxseats);
        ArrayList<Assignment2_Car> seatCapacityList = carDirectory.minMaxseatsCount(minS, maxS);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,seatCapacityList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnSeatCapacity1ActionPerformed

    private void btnFirstAvailableCar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstAvailableCar1ActionPerformed
        // TODO add your handling code here:
        String firstAvailable = "Yes";
        ArrayList<Assignment2_Car> availableFirstList = carDirectory.firstAvailable(firstAvailable);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,availableFirstList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnFirstAvailableCar1ActionPerformed

    private void btnLastUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCarDetails.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Assignment2_Car car = (Assignment2_Car) tblCarDetails.getValueAt(selectedRow, 0);
            txtLastUpdated.setText(car.getDate());
        }

    }//GEN-LAST:event_btnLastUpdateActionPerformed

    private void txtLastUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastUpdatedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastUpdatedActionPerformed

    private void btnAllAvailableCar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllAvailableCar1ActionPerformed
        // TODO add your handling code here:
        String available = "Yes";
        ArrayList<Assignment2_Car> allAvailableList = carDirectory.allAvailable(available);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,allAvailableList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAllAvailableCar1ActionPerformed

    private void btnUnavailableCar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnavailableCar1ActionPerformed
        // TODO add your handling code here:
        String unavailable = "Yes";
        ArrayList<Assignment2_Car> unavailableList = carDirectory.unavailableCar(unavailable);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,unavailableList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUnavailableCar1ActionPerformed

    private void btnserialNoS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnserialNoS1ActionPerformed
        // TODO add your handling code here:
        String serialNo = txtserialNoS.getText();
        ArrayList<Assignment2_Car> serialList = carDirectory.serialNoList(serialNo);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,serialList);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnserialNoS1ActionPerformed

    private void txtserialNoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserialNoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtserialNoSActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String registeredwithUber = "Yes";
        ArrayList<Assignment2_Car> searchregisteredwithUber = carDirectory.uberUsedCarList(registeredwithUber);
        SerachListJPanel panel = new SerachListJPanel(userProcessContainer,searchregisteredwithUber);
        userProcessContainer.add("SerachListJPanel",panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllAvailableCar1;
    private javax.swing.JButton btnBrand1;
    private javax.swing.JButton btnCertificate;
    private javax.swing.JButton btnCity1;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnFirstAvailableCar1;
    private javax.swing.JButton btnLastUpdate;
    private javax.swing.JButton btnModelNo1;
    private javax.swing.JButton btnSeatCapacity1;
    private javax.swing.JButton btnUnavailableCar1;
    private javax.swing.JButton btnViewDetails1;
    private javax.swing.JButton btnYear;
    private javax.swing.JButton btnserialNoS1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMinSeats;
    private javax.swing.JLabel lblMinSeats1;
    private javax.swing.JTable tblCarDetails;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtLastUpdated;
    private javax.swing.JTextField txtMaxSeats;
    private javax.swing.JTextField txtMinSeats;
    private javax.swing.JTextField txtModelNo;
    private javax.swing.JTextField txtYearSearch;
    private javax.swing.JTextField txtserialNoS;
    // End of variables declaration//GEN-END:variables
}
