/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;


import assignment2_car.Assignment2_Car;
import assignment2_car.Directory_Car;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author mhetr
 */
public class ViewJPanel extends javax.swing.JPanel {
    private Assignment2_Car car;
    private Directory_Car carDirectory;
    public String checkbox;
    private JPanel userProcessContainer;
    /**
     * Creates new form ViewJPanel
     */
     ViewJPanel(JPanel userProcessContainer, Assignment2_Car car, Directory_Car carDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.car = car;
        this.carDirectory = carDirectory;
        populateDetails();
        btnSave1.setEnabled(false);
        btnUpdate1.setEnabled(true);
    }
     private void populateDetails(){
        txtTransitLevel.setSelectedItem(car.getTransitLevel());
        txtBrand1.setText(car.getbrand());
        txtmodelNo1.setText(car.getmodelNo());
        txtserialNo1.setText(car.getserialNo());
        txtCity1.setText(car.getCity());
        txtCost1.setText(Double.toString(car.getPrice()));
        txtNoOfSeats.setText(Integer.toString(car.getSeatCount()));
        txtManufactureYear1.setText(Integer.toString(car.getManufactureYear()));
        txtmaintenanceCertificate1.setSelectedItem(car.getmaintenanceCertificate());
        checkBox1.setSelected(car.getAvailablity().equalsIgnoreCase("Yes"));
        txtRegisterWithUber1.setSelectedItem(car.getregisteredwithUber());
        txtDate1.setText(car.getDate());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEnterDetails = new javax.swing.JLabel();
        txtCost1 = new javax.swing.JTextField();
        lblManufactureYear = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblManufacturedBy = new javax.swing.JLabel();
        lblTransitLevel = new javax.swing.JLabel();
        lblModelNumber = new javax.swing.JLabel();
        txtBrand1 = new javax.swing.JTextField();
        txtTransitLevel = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        txtmodelNo1 = new javax.swing.JTextField();
        lblSerialNo = new javax.swing.JLabel();
        txtserialNo1 = new javax.swing.JTextField();
        lblAvailableCity = new javax.swing.JLabel();
        txtManufactureYear1 = new javax.swing.JTextField();
        txtCity1 = new javax.swing.JTextField();
        btnUpdate1 = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        lblAvailable = new javax.swing.JLabel();
        lblMaintenanceCertificate = new javax.swing.JLabel();
        txtRegisterWithUber1 = new javax.swing.JComboBox();
        lblNoOfSeats = new javax.swing.JLabel();
        lblRegisterWithUber = new javax.swing.JLabel();
        txtNoOfSeats = new javax.swing.JTextField();
        txtmaintenanceCertificate1 = new javax.swing.JComboBox();
        lblDate = new javax.swing.JLabel();
        txtDate1 = new javax.swing.JTextField();
        checkBox1 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(107, 107, 127));

        lblEnterDetails.setBackground(new java.awt.Color(0, 0, 0));
        lblEnterDetails.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblEnterDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnterDetails.setText("View Details");

        txtCost1.setEditable(false);
        txtCost1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCost1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCost1.setBorder(null);
        txtCost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCost1ActionPerformed(evt);
            }
        });

        lblManufactureYear.setBackground(new java.awt.Color(0, 0, 0));
        lblManufactureYear.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblManufactureYear.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblManufactureYear.setText("Manufacture Year:");

        lblPrice.setBackground(new java.awt.Color(0, 0, 0));
        lblPrice.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrice.setText("Cost");

        lblManufacturedBy.setBackground(new java.awt.Color(0, 0, 0));
        lblManufacturedBy.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblManufacturedBy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblManufacturedBy.setText("Brand Name");

        lblTransitLevel.setBackground(new java.awt.Color(0, 0, 0));
        lblTransitLevel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTransitLevel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTransitLevel.setText("Transit Level");

        lblModelNumber.setBackground(new java.awt.Color(0, 0, 0));
        lblModelNumber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblModelNumber.setText("Model Number:");

        txtBrand1.setEditable(false);
        txtBrand1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtBrand1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtBrand1.setBorder(null);

        txtTransitLevel.setEditable(true);
        txtTransitLevel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtTransitLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Hatchback", "Sedan", "SUV", "Crossover", "Convertible" }));
        txtTransitLevel.setEnabled(false);
        txtTransitLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransitLevelActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnBack.setText("< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtmodelNo1.setEditable(false);
        txtmodelNo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtmodelNo1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtmodelNo1.setBorder(null);

        lblSerialNo.setBackground(new java.awt.Color(0, 0, 0));
        lblSerialNo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblSerialNo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSerialNo.setText("Serial Number:");

        txtserialNo1.setEditable(false);
        txtserialNo1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtserialNo1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtserialNo1.setBorder(null);

        lblAvailableCity.setBackground(new java.awt.Color(0, 0, 0));
        lblAvailableCity.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAvailableCity.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAvailableCity.setText("City Available:");

        txtManufactureYear1.setEditable(false);
        txtManufactureYear1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtManufactureYear1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtManufactureYear1.setBorder(null);

        txtCity1.setEditable(false);
        txtCity1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCity1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtCity1.setBorder(null);

        btnUpdate1.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnSave1.setBackground(new java.awt.Color(255, 255, 255));
        btnSave1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        lblAvailable.setBackground(new java.awt.Color(0, 0, 0));
        lblAvailable.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblAvailable.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAvailable.setText("Available:");

        lblMaintenanceCertificate.setBackground(new java.awt.Color(0, 0, 0));
        lblMaintenanceCertificate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblMaintenanceCertificate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblMaintenanceCertificate.setText("Maintenance Certificate:");

        txtRegisterWithUber1.setEditable(true);
        txtRegisterWithUber1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtRegisterWithUber1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Yes", "No" }));
        txtRegisterWithUber1.setEnabled(false);
        txtRegisterWithUber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisterWithUber1ActionPerformed(evt);
            }
        });

        lblNoOfSeats.setBackground(new java.awt.Color(0, 0, 0));
        lblNoOfSeats.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblNoOfSeats.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNoOfSeats.setText("No of Seats:");

        lblRegisterWithUber.setBackground(new java.awt.Color(0, 0, 0));
        lblRegisterWithUber.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblRegisterWithUber.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblRegisterWithUber.setText("Used By Uber:");

        txtNoOfSeats.setEditable(false);
        txtNoOfSeats.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNoOfSeats.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtNoOfSeats.setBorder(null);

        txtmaintenanceCertificate1.setEditable(true);
        txtmaintenanceCertificate1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        txtmaintenanceCertificate1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Valid", "Expired" }));
        txtmaintenanceCertificate1.setEnabled(false);
        txtmaintenanceCertificate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaintenanceCertificate1ActionPerformed(evt);
            }
        });

        lblDate.setBackground(new java.awt.Color(0, 0, 0));
        lblDate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDate.setText("Date:");

        txtDate1.setEditable(false);
        txtDate1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDate1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtDate1.setBorder(null);
        txtDate1.setEnabled(false);

        checkBox1.setEnabled(false);
        checkBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnBack))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMaintenanceCertificate)
                                    .addComponent(lblAvailable))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmaintenanceCertificate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addComponent(lblRegisterWithUber)
                                .addGap(18, 18, 18)
                                .addComponent(txtRegisterWithUber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblPrice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCost1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblManufacturedBy)
                                        .addGap(44, 44, 44)
                                        .addComponent(txtBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblAvailableCity)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTransitLevel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTransitLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(93, 93, 93)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSerialNo)
                                            .addComponent(lblModelNumber)
                                            .addComponent(lblNoOfSeats))
                                        .addGap(36, 36, 36)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmodelNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtserialNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblManufactureYear)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtManufactureYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(247, 247, 247))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEnterDetails)
                                    .addComponent(btnBack))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblManufacturedBy)
                                            .addComponent(txtBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSerialNo)
                                            .addComponent(txtserialNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblModelNumber)
                                    .addComponent(lblAvailableCity)
                                    .addComponent(txtCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmodelNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTransitLevel)
                                    .addComponent(txtTransitLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNoOfSeats)
                                    .addComponent(txtNoOfSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblPrice))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblManufactureYear)
                                            .addComponent(txtManufactureYear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(txtCost1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDate)
                                    .addComponent(txtDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(lblRegisterWithUber))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMaintenanceCertificate)
                                            .addComponent(txtmaintenanceCertificate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtRegisterWithUber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)))
                                .addComponent(lblAvailable))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkBox1)))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate1)
                    .addComponent(btnSave1))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 34, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCost1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCost1ActionPerformed

    private void txtTransitLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransitLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTransitLevelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ManageJPanel panel = new ManageJPanel(userProcessContainer, carDirectory);
        userProcessContainer.add("ManageJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        // TODO add your handling code here:
        
        
        txtTransitLevel.setEditable(true);
        txtBrand1.setEditable(true);
        txtmodelNo1.setEditable(true);
        txtserialNo1.setEditable(true);
        txtCity1.setEditable(true);
        txtNoOfSeats.setEditable(true);
        txtCost1.setEditable(true);
        txtManufactureYear1.setEditable(true);
        txtmaintenanceCertificate1.setEditable(true);
        txtRegisterWithUber1.setEditable(true);
        txtTransitLevel.setEnabled(true);
        txtBrand1.setEnabled(true);
        txtmodelNo1.setEnabled(true);
        txtserialNo1.setEnabled(true);
        txtCity1.setEnabled(true);
        txtNoOfSeats.setEnabled(true);
        txtCost1.setEnabled(true);
        txtManufactureYear1.setEnabled(true);
        txtmaintenanceCertificate1.setEnabled(true);
        checkBox1.setEnabled(true);
        txtRegisterWithUber1.setEnabled(true);
        txtDate1.setEnabled(false);
        btnSave1.setEnabled(true);
        btnUpdate1.setEnabled(false);
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        // TODO add your handling code here:
        DateFormat dateformat = new SimpleDateFormat("MM:dd:YYYY");
        Date dateObj = new Date();
        String j = dateformat.format(dateObj);
        car.setDate(j);
        
        String transitLevel = txtTransitLevel.getSelectedItem().toString();
        if (transitLevel == null || transitLevel.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select a Transit Level!");
            return;
        }
        String brand = txtBrand1.getText();
        if (brand == null || brand.equals("")) {
            JOptionPane.showMessageDialog(null, "Brand Name is empty!");
            return;
        }
        String modelNo = txtmodelNo1.getText();
        if (modelNo == null || modelNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Model Number is empty!");
            return;
        }
        String serialNo = txtserialNo1.getText();
        if (serialNo == null || serialNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Serial Number is empty!");
            return;
        }
        
        String city = txtCity1.getText();
        if (city == null || city.equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid City Name!");
            return;
        }
       
        
        
        String seatCount = txtNoOfSeats.getText();
        try{
            
            
            
            Integer.parseInt(seatCount);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a integer value for No of Seats");
            return;
        }
        String cost = txtCost1.getText();
        try{
            Double.parseDouble(cost);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a Double value for Cost");
            return;
        }
        String manufactureYear = txtManufactureYear1.getText();
        try{
            Integer.parseInt(manufactureYear);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Please type in a Integer value for Manufactured Year");
            return;
        }
        String maintenanceCertificate = txtmaintenanceCertificate1.getSelectedItem().toString();
        if (maintenanceCertificate == null || maintenanceCertificate.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select the status of maintenance certificate");
            return;
        }
        
        String registeredwithUber = txtRegisterWithUber1.getSelectedItem().toString();
        if (registeredwithUber == null || registeredwithUber.equalsIgnoreCase("Select")) {
            JOptionPane.showMessageDialog(null, "Please select Registration with Uber");
            return;
        }
       
      

        txtTransitLevel.setEnabled(false);
        txtBrand1.setEditable(false);
        txtmodelNo1.setEditable(false);
        txtserialNo1.setEditable(false);
        txtCity1.setEditable(false);
        txtNoOfSeats.setEditable(false);
        txtCost1.setEditable(false);
        txtManufactureYear1.setEditable(false);
        txtmaintenanceCertificate1.setEnabled(false);
        checkBox1.setEnabled(false);
        txtRegisterWithUber1.setEnabled(false);
        txtDate1.setEnabled(false);
        btnSave1.setEnabled(false);
        btnUpdate1.setEnabled(true);
        car.setTransitLevel(txtTransitLevel.getSelectedItem().toString());
        car.setbrand(txtBrand1.getText());
        car.setmodelNo(txtmodelNo1.getText());
        car.setserialNo(txtserialNo1.getText());
        car.setCity(txtCity1.getText());
        car.setSeatCount(Integer.parseInt(txtNoOfSeats.getText()));
        car.setPrice(Double.parseDouble(txtCost1.getText()));
        car.setManufactureYear(Integer.parseInt(txtManufactureYear1.getText()));
        car.setmaintenanceCertificate(txtmaintenanceCertificate1.getSelectedItem().toString());
        car.setAvailablity(checkbox);
        car.setregisteredwithUber(txtRegisterWithUber1.getSelectedItem().toString());
        btnSave1.setEnabled(false);
        btnUpdate1.setEnabled(true);
        JOptionPane.showMessageDialog(null,"Car details updated successfully!");
        
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void txtRegisterWithUber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisterWithUber1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisterWithUber1ActionPerformed

    private void txtmaintenanceCertificate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaintenanceCertificate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaintenanceCertificate1ActionPerformed

    private void checkBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox1ActionPerformed
        // TODO add your handling code here:
        if(checkBox1.isSelected())
        {
            checkbox = "Yes";
        }
        else
        {
            checkbox = "No";
        }
    }//GEN-LAST:event_checkBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvailable;
    private javax.swing.JLabel lblAvailableCity;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEnterDetails;
    private javax.swing.JLabel lblMaintenanceCertificate;
    private javax.swing.JLabel lblManufactureYear;
    private javax.swing.JLabel lblManufacturedBy;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblNoOfSeats;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblRegisterWithUber;
    private javax.swing.JLabel lblSerialNo;
    private javax.swing.JLabel lblTransitLevel;
    private javax.swing.JTextField txtBrand1;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtCost1;
    private javax.swing.JTextField txtDate1;
    private javax.swing.JTextField txtManufactureYear1;
    private javax.swing.JTextField txtNoOfSeats;
    private javax.swing.JComboBox txtRegisterWithUber1;
    private javax.swing.JComboBox txtTransitLevel;
    private javax.swing.JComboBox txtmaintenanceCertificate1;
    private javax.swing.JTextField txtmodelNo1;
    private javax.swing.JTextField txtserialNo1;
    // End of variables declaration//GEN-END:variables
}
